spring:
  datasource:
    url: jdbc:h2:file:~/data/meta-collector
    username: user
    password: qwerty
    driver-class-name: org.h2.Driver
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show_sql: false
      use_sql_comments: true
      format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true